adding lint

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -22,6 +22,20 @@ jobs:
     - name: Check out code into the Go module directory
       uses: actions/checkout@v2
 
+    - name: Lint
+      run: |
+        echo "Linting Go Files... If this fails, run 'go fmt ./... && (cd samples && go fmt ./...)' to fix"
+
+        # This runs a go fmt on each file without using the 'go fmt ./...' syntax.
+        # This is advantageous because it avoids having to download all of the go
+        # dependencies that would have been triggered by using the './...' syntax.
+        FILES_WITH_FMT_ISSUES=$(find . -name "*.go" | grep -v '.terraform' | xargs gofmt -l | wc -l)
+
+        # convert to integer...
+        FILES_WITH_FMT_ISSUES=$(($FILES_WITH_FMT_ISSUES + 0))
+
+        exit $FILES_WITH_FMT_ISSUES
+
     - name: Get dependencies
       run: |
         go get -v -t -d ./...
